[package]
name = "net"
version = "0.1.0"
edition = "2024"

[dependencies]
minecraft_protocol = { path = "../minecraft_protocol" }
flate2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio-test = "0.4.4"
